const productList = [
    {
        categoryId: 1,
        categoryName: "juices",
        name: "СОКИ",
        catalog: [
            {
                id: 1,
                img: '/-VitaJuice/img/productList/product-img-01.png',
                title: 'ЛАССИ',
                size: '500',
                price: 375,
                bonus: '0',
            },
            {
                id: 2,
                img: '/-VitaJuice/img/productList/product-img-02.png',
                title: 'МИКС',
                size: '500',
                price: 400,
                bonus: '20',
            },
            {
                id: 3,
                img: '/-VitaJuice/img/productList/product-img-03.png',
                title: 'БОУЛ',
                size: '500',
                price: 450,
                bonus: '0',
            },
            {
                id: 4,
                img: '/-VitaJuice/img/productList/product-img-04.png',
                title: 'АПЕЛЬСИНОВЫЙ СОК',
                size: '500',
                price: 400,
                bonus: '0',
            },
            {
                id: 5,
                img: '/-VitaJuice/img/productList/product-img-05.png',
                title: 'СМУЗИ',
                size: '500',
                price: 385,
                bonus: '0',
            },
            {
                id: 6,
                img: '/-VitaJuice/img/productList/product-img-06.png',
                title: 'ДЕТОКС',
                size: '500',
                price: 500,
                bonus: '50',
            },
            {
                id: 7,
                img: '/-VitaJuice/img/productList/product-img-07.png',
                title: 'ДОКТОР',
                size: '500',
                price: 375,
                bonus: '0',
            },
            {
                id: 8,
                img: '/-VitaJuice/img/productList/product-img-08.png',
                title: 'ГРАНАТОВЫЙ СОК',
                size: '500',
                composition: 'гранат, лед',
                price: 500,
                bonus: '20',
            },
            {
                id: 9,
                img: '/-VitaJuice/img/productList/product-img-09.png',
                title: 'ГРИН',
                size: '500',
                price: 450,
                bonus: '0',
            },
            {
                id: 10,
                img: '/-VitaJuice/img/productList/product-img-01.png',
                title: 'ЛАССИ',
                size: '500',
                price: 375,
                bonus: '0',
            },
            {
                id: 11,
                img: '/-VitaJuice/img/productList/product-img-02.png',
                title: 'МИКС',
                size: '500',
                price: 400,
                bonus: '20',
            },
            {
                id: 12,
                img: '/-VitaJuice/img/productList/product-img-03.png',
                title: 'БОУЛ',
                size: '500',
                price: 450,
                bonus: '0',
            },
        ]
    },

    {
        categoryId: 2,
        categoryName: "mixes",
        name: "МИКСЫ",
        catalog: [
            {
                id: 1,
                img: '/-VitaJuice/img/productList/product-img-01.png',
                title: 'ЛАССИ',
                size: '500',
                price: '375',
                bonus: '0',
            },
            {
                id: 2,
                img: '/-VitaJuice/img/productList/product-img-02.png',
                title: 'МИКС',
                size: '500',
                price: '400',
                bonus: '20',
            },
            {
                id: 3,
                img: '/-VitaJuice/img/productList/product-img-03.png',
                title: 'БОУЛ',
                size: '500',
                price: '450',
                bonus: '0',
            },
            {
                id: 4,
                img: '/-VitaJuice/img/productList/product-img-04.png',
                title: 'АПЕЛЬСИНОВЫЙ СОК',
                size: '500',
                price: '400',
                bonus: '0',
            },
            {
                id: 5,
                img: '/-VitaJuice/img/productList/product-img-05.png',
                title: 'СМУЗИ',
                size: '500',
                price: '385',
                bonus: '0',
            },
            {
                id: 6,
                img: '/-VitaJuice/img/productList/product-img-06.png',
                title: 'ДЕТОКС',
                size: '500',
                price: '500',
                bonus: '50',
            },
            {
                id: 7,
                img: '/-VitaJuice/img/productList/product-img-07.png',
                title: 'ДОКТОР',
                size: '500',
                price: '375',
                bonus: '0',
            },
            {
                id: 8,
                img: '/-VitaJuice/img/productList/product-img-08.png',
                title: 'ГРАНАТОВЫЙ СОК',
                size: '500',
                price: '500',
                bonus: '20',
            },
            {
                id: 9,
                img: '/-VitaJuice/img/productList/product-img-09.png',
                title: 'ГРИН',
                size: '500',
                price: '450',
                bonus: '0',
            },
            {
                id: 10,
                img: '/-VitaJuice/img/productList/product-img-01.png',
                title: 'ЛАССИ',
                size: '500',
                price: '375',
                bonus: '0',
            },
            {
                id: 11,
                img: '/-VitaJuice/img/productList/product-img-02.png',
                title: 'МИКС',
                size: '500',
                price: '400',
                bonus: '20',
            },
            {
                id: 12,
                img: '/-VitaJuice/img/productList/product-img-03.png',
                title: 'БОУЛ',
                size: '500',
                price: '450',
                bonus: '0',
            },
        ]
    },

    {
        categoryId: 3,
        categoryName: "smoothie",
        name: "СМУЗИ",
        catalog: [
            {
                id: 1,
                img: '/-VitaJuice/img/productList/product-img-01.png',
                title: 'ЛАССИ',
                size: '500',
                price: '375',
                bonus: '0',
            },
            {
                id: 2,
                img: '/-VitaJuice/img/productList/product-img-02.png',
                title: 'МИКС',
                size: '500',
                price: '400',
                bonus: '20',
            },
            {
                id: 3,
                img: '/-VitaJuice/img/productList/product-img-03.png',
                title: 'БОУЛ',
                size: '500',
                price: '450',
                bonus: '0',
            },
            {
                id: 4,
                img: '/-VitaJuice/img/productList/product-img-04.png',
                title: 'АПЕЛЬСИНОВЫЙ СОК',
                size: '500',
                price: '400',
                bonus: '0',
            },
            {
                id: 5,
                img: '/-VitaJuice/img/productList/product-img-05.png',
                title: 'СМУЗИ',
                size: '500',
                price: '385',
                bonus: '0',
            },
            {
                id: 6,
                img: '/-VitaJuice/img/productList/product-img-06.png',
                title: 'ДЕТОКС',
                size: '500',
                price: '500',
                bonus: '50',
            },
            {
                id: 7,
                img: '/-VitaJuice/img/productList/product-img-07.png',
                title: 'ДОКТОР',
                size: '500',
                price: '375',
                bonus: '0',
            },
            {
                id: 8,
                img: '/-VitaJuice/img/productList/product-img-08.png',
                title: 'ГРАНАТОВЫЙ СОК',
                size: '500',
                price: '500',
                bonus: '20',
            },
            {
                id: 9,
                img: '/-VitaJuice/img/productList/product-img-09.png',
                title: 'ГРИН',
                size: '500',
                price: '450',
                bonus: '0',
            },
            {
                id: 10,
                img: '/-VitaJuice/img/productList/product-img-01.png',
                title: 'ЛАССИ',
                size: '500',
                price: '375',
                bonus: '0',
            },
            {
                id: 11,
                img: '/-VitaJuice/img/productList/product-img-02.png',
                title: 'МИКС',
                size: '500',
                price: '400',
                bonus: '20',
            },
            {
                id: 12,
                img: '/-VitaJuice/img/productList/product-img-03.png',
                title: 'БОУЛ',
                size: '500',
                price: '450',
                bonus: '0',
            },
        ]
    },

    {
        categoryId: 4,
        categoryName: "lassi",
        name: "ЛАССИ",
        catalog: [
            {
                id: 1,
                img: '/-VitaJuice/img/productList/product-img-01.png',
                title: 'ЛАССИ',
                size: '500',
                price: '375',
                bonus: '0',
            },
            {
                id: 2,
                img: '/-VitaJuice/img/productList/product-img-02.png',
                title: 'МИКС',
                size: '500',
                price: '400',
                bonus: '20',
            },
            {
                id: 3,
                img: '/-VitaJuice/img/productList/product-img-03.png',
                title: 'БОУЛ',
                size: '500',
                price: '450',
                bonus: '0',
            },
            {
                id: 4,
                img: '/-VitaJuice/img/productList/product-img-04.png',
                title: 'АПЕЛЬСИНОВЫЙ СОК',
                size: '500',
                price: '400',
                bonus: '0',
            },
            {
                id: 5,
                img: '/-VitaJuice/img/productList/product-img-05.png',
                title: 'СМУЗИ',
                size: '500',
                price: '385',
                bonus: '0',
            },
            {
                id: 6,
                img: '/-VitaJuice/img/productList/product-img-06.png',
                title: 'ДЕТОКС',
                size: '500',
                price: '500',
                bonus: '50',
            },
            {
                id: 7,
                img: '/-VitaJuice/img/productList/product-img-07.png',
                title: 'ДОКТОР',
                size: '500',
                price: '375',
                bonus: '0',
            },
            {
                id: 8,
                img: '/-VitaJuice/img/productList/product-img-08.png',
                title: 'ГРАНАТОВЫЙ СОК',
                size: '500',
                price: '500',
                bonus: '20',
            },
            {
                id: 9,
                img: '/-VitaJuice/img/productList/product-img-09.png',
                title: 'ГРИН',
                size: '500',
                price: '450',
                bonus: '0',
            },
            {
                id: 10,
                img: '/-VitaJuice/img/productList/product-img-01.png',
                title: 'ЛАССИ',
                size: '500',
                price: '375',
                bonus: '0',
            },
            {
                id: 11,
                img: '/-VitaJuice/img/productList/product-img-02.png',
                title: 'МИКС',
                size: '500',
                price: '400',
                bonus: '20',
            },
            {
                id: 12,
                img: '/-VitaJuice/img/productList/product-img-03.png',
                title: 'БОУЛ',
                size: '500',
                price: '450',
                bonus: '0',
            },
        ]
    },

    {
        categoryId: 5,
        categoryName: "detox",
        name: "ДЕТОКС",
        catalog: [
            {
                id: 1,
                img: '/-VitaJuice/img/productList/product-img-01.png',
                title: 'ЛАССИ',
                size: '500',
                price: '375',
                bonus: '0',
            },
            {
                id: 2,
                img: '/-VitaJuice/img/productList/product-img-02.png',
                title: 'МИКС',
                size: '500',
                price: '400',
                bonus: '20',
            },
            {
                id: 3,
                img: '/-VitaJuice/img/productList/product-img-03.png',
                title: 'БОУЛ',
                size: '500',
                price: '450',
                bonus: '0',
            },
            {
                id: 4,
                img: '/-VitaJuice/img/productList/product-img-04.png',
                title: 'АПЕЛЬСИНОВЫЙ СОК',
                size: '500',
                price: '400',
                bonus: '0',
            },
            {
                id: 5,
                img: '/-VitaJuice/img/productList/product-img-05.png',
                title: 'СМУЗИ',
                size: '500',
                price: '385',
                bonus: '0',
            },
            {
                id: 6,
                img: '/-VitaJuice/img/productList/product-img-06.png',
                title: 'ДЕТОКС',
                size: '500',
                price: '500',
                bonus: '50',
            },
            {
                id: 7,
                img: '/-VitaJuice/img/productList/product-img-07.png',
                title: 'ДОКТОР',
                size: '500',
                price: '375',
                bonus: '0',
            },
            {
                id: 8,
                img: '/-VitaJuice/img/productList/product-img-08.png',
                title: 'ГРАНАТОВЫЙ СОК',
                size: '500',
                price: '500',
                bonus: '20',
            },
            {
                id: 9,
                img: '/-VitaJuice/img/productList/product-img-09.png',
                title: 'ГРИН',
                size: '500',
                price: '450',
                bonus: '0',
            },
            {
                id: 10,
                img: '/-VitaJuice/img/productList/product-img-01.png',
                title: 'ЛАССИ',
                size: '500',
                price: '375',
                bonus: '0',
            },
            {
                id: 11,
                img: '/-VitaJuice/img/productList/product-img-02.png',
                title: 'МИКС',
                size: '500',
                price: '400',
                bonus: '20',
            },
            {
                id: 12,
                img: '/-VitaJuice/img/productList/product-img-03.png',
                title: 'БОУЛ',
                size: '500',
                price: '450',
                bonus: '0',
            },
        ]
    },

    {
        categoryId: 6,
        categoryName: "bowls",
        name: "БОУЛЫ",
        catalog: [
            {
                id: 1,
                img: '/-VitaJuice/img/productList/product-img-01.png',
                title: 'ЛАССИ',
                size: '500',
                price: '375',
                bonus: '0',
            },
            {
                id: 2,
                img: '/-VitaJuice/img/productList/product-img-02.png',
                title: 'МИКС',
                size: '500',
                price: '400',
                bonus: '20',
            },
            {
                id: 3,
                img: '/-VitaJuice/img/productList/product-img-03.png',
                title: 'БОУЛ',
                size: '500',
                price: '450',
                bonus: '0',
            },
            {
                id: 4,
                img: '/-VitaJuice/img/productList/product-img-04.png',
                title: 'АПЕЛЬСИНОВЫЙ СОК',
                size: '500',
                price: '400',
                bonus: '0',
            },
            {
                id: 5,
                img: '/-VitaJuice/img/productList/product-img-05.png',
                title: 'СМУЗИ',
                size: '500',
                price: '385',
                bonus: '0',
            },
            {
                id: 6,
                img: '/-VitaJuice/img/productList/product-img-06.png',
                title: 'ДЕТОКС',
                size: '500',
                price: '500',
                bonus: '50',
            },
            {
                id: 7,
                img: '/-VitaJuice/img/productList/product-img-07.png',
                title: 'ДОКТОР',
                size: '500',
                price: '375',
                bonus: '0',
            },
            {
                id: 8,
                img: '/-VitaJuice/img/productList/product-img-08.png',
                title: 'ГРАНАТОВЫЙ СОК',
                size: '500',
                price: '500',
                bonus: '20',
            },
            {
                id: 9,
                img: '/-VitaJuice/img/productList/product-img-09.png',
                title: 'ГРИН',
                size: '500',
                price: '450',
                bonus: '0',
            },
            {
                id: 10,
                img: '/-VitaJuice/img/productList/product-img-01.png',
                title: 'ЛАССИ',
                size: '500',
                price: '375',
                bonus: '0',
            },
            {
                id: 11,
                img: '/-VitaJuice/img/productList/product-img-02.png',
                title: 'МИКС',
                size: '500',
                price: '400',
                bonus: '20',
            },
            {
                id: 12,
                img: '/-VitaJuice/img/productList/product-img-03.png',
                title: 'БОУЛ',
                size: '500',
                price: '450',
                bonus: '0',
            },
        ]
    },

    {
        categoryId: 7,
        categoryName: "salads",
        name: "САЛАТЫ",
        catalog: [
            {
                id: 1,
                img: '/-VitaJuice/img/productList/product-img-01.png',
                title: 'ЛАССИ',
                size: '500',
                price: '375',
                bonus: '0',
            },
            {
                id: 2,
                img: '/-VitaJuice/img/productList/product-img-02.png',
                title: 'МИКС',
                size: '500',
                price: '400',
                bonus: '20',
            },
            {
                id: 3,
                img: '/-VitaJuice/img/productList/product-img-03.png',
                title: 'БОУЛ',
                size: '500',
                price: '450',
                bonus: '0',
            },
            {
                id: 4,
                img: '/-VitaJuice/img/productList/product-img-04.png',
                title: 'АПЕЛЬСИНОВЫЙ СОК',
                size: '500',
                price: '400',
                bonus: '0',
            },
            {
                id: 5,
                img: '/-VitaJuice/img/productList/product-img-05.png',
                title: 'СМУЗИ',
                size: '500',
                price: '385',
                bonus: '0',
            },
            {
                id: 6,
                img: '/-VitaJuice/img/productList/product-img-06.png',
                title: 'ДЕТОКС',
                size: '500',
                price: '500',
                bonus: '50',
            },
            {
                id: 7,
                img: '/-VitaJuice/img/productList/product-img-07.png',
                title: 'ДОКТОР',
                size: '500',
                price: '375',
                bonus: '0',
            },
            {
                id: 8,
                img: '/-VitaJuice/img/productList/product-img-08.png',
                title: 'ГРАНАТОВЫЙ СОК',
                size: '500',
                price: '500',
                bonus: '20',
            },
            {
                id: 9,
                img: '/-VitaJuice/img/productList/product-img-09.png',
                title: 'ГРИН',
                size: '500',
                price: '450',
                bonus: '0',
            },
            {
                id: 10,
                img: '/-VitaJuice/img/productList/product-img-01.png',
                title: 'ЛАССИ',
                size: '500',
                price: '375',
                bonus: '0',
            },
            {
                id: 11,
                img: '/-VitaJuice/img/productList/product-img-02.png',
                title: 'МИКС',
                size: '500',
                price: '400',
                bonus: '20',
            },
            {
                id: 12,
                img: '/-VitaJuice/img/productList/product-img-03.png',
                title: 'БОУЛ',
                size: '500',
                price: '450',
                bonus: '0',
            },
        ]
    },

    {
        categoryId: 8,
        categoryName: "healthy-food",
        name: "ЗДОРОВАЯ ЕДА",
        catalog: [
            {
                id: 1,
                img: '/-VitaJuice/img/productList/product-img-01.png',
                title: 'ЛАССИ',
                size: '500',
                price: '375',
                bonus: '0',
            },
            {
                id: 2,
                img: '/-VitaJuice/img/productList/product-img-02.png',
                title: 'МИКС',
                size: '500',
                price: '400',
                bonus: '20',
            },
            {
                id: 3,
                img: '/-VitaJuice/img/productList/product-img-03.png',
                title: 'БОУЛ',
                size: '500',
                price: '450',
                bonus: '0',
            },
            {
                id: 4,
                img: '/-VitaJuice/img/productList/product-img-04.png',
                title: 'АПЕЛЬСИНОВЫЙ СОК',
                size: '500',
                price: '400',
                bonus: '0',
            },
            {
                id: 5,
                img: '/-VitaJuice/img/productList/product-img-05.png',
                title: 'СМУЗИ',
                size: '500',
                price: '385',
                bonus: '0',
            },
            {
                id: 6,
                img: '/-VitaJuice/img/productList/product-img-06.png',
                title: 'ДЕТОКС',
                size: '500',
                price: '500',
                bonus: '50',
            },
            {
                id: 7,
                img: '/-VitaJuice/img/productList/product-img-07.png',
                title: 'ДОКТОР',
                size: '500',
                price: '375',
                bonus: '0',
            },
            {
                id: 8,
                img: '/-VitaJuice/img/productList/product-img-08.png',
                title: 'ГРАНАТОВЫЙ СОК',
                size: '500',
                price: '500',
                bonus: '20',
            },
            {
                id: 9,
                img: '/-VitaJuice/img/productList/product-img-09.png',
                title: 'ГРИН',
                size: '500',
                price: '450',
                bonus: '0',
            },
            {
                id: 10,
                img: '/-VitaJuice/img/productList/product-img-01.png',
                title: 'ЛАССИ',
                size: '500',
                price: '375',
                bonus: '0',
            },
            {
                id: 11,
                img: '/-VitaJuice/img/productList/product-img-02.png',
                title: 'МИКС',
                size: '500',
                price: '400',
                bonus: '20',
            },
            {
                id: 12,
                img: '/-VitaJuice/img/productList/product-img-03.png',
                title: 'БОУЛ',
                size: '500',
                price: '450',
                bonus: '0',
            },
        ]
    },
]

export default productList